package com.example.stability.mvp.advanced

import android.util.Log

/**
 * MVP 高级完整实现示例
 * 本示例演示一个包含多个功能模块的完整 MVP 应用
 */
class MVPAdvancedExample {
    
    companion object {
        private const val TAG = "MVP"
    }
    
    /**
     * 启动高级示例
     * 设计原因：提供一个入口点来演示完整的 MVP 应用结构
     * 技术目的：初始化并运行 MVP 高级示例
     */
    fun start() {
        Log.d(TAG, "=== MVP 高级完整实现示例启动 ===")
        
        // 1. 多模块架构
        demonstrateMultiModuleArchitecture()
        
        // 2. 基类设计
        demonstrateBaseClassDesign()
        
        // 3. 依赖注入
        demonstrateDependencyInjection()
        
        // 4. 单元测试
        demonstrateUnitTesting()
        
        // 5. 最佳实践
        demonstrateBestPractices()
        
        Log.d(TAG, "=== MVP 高级完整实现示例完成 ===")
    }
    
    /**
     * 演示多模块架构
     * 设计原因：说明如何组织大型 MVP 应用的代码结构
     * 技术目的：提供清晰的模块划分方法
     */
    private fun demonstrateMultiModuleArchitecture() {
        Log.d(TAG, "")
        Log.d(TAG, "========== 多模块架构 ==========")
        Log.d(TAG, "")
        Log.d(TAG, "大型 MVP 应用的目录结构：")
        Log.d(TAG, "")
        Log.d(TAG, "app/src/main/java/com/example/app/")
        Log.d(TAG, "├── base/")
        Log.d(TAG, "│   ├── BaseView.kt")
        Log.d(TAG, "│   ├── BasePresenter.kt")
        Log.d(TAG, "│   └── BaseActivity.kt")
        Log.d(TAG, "├── data/")
        Log.d(TAG, "│   ├── api/")
        Log.d(TAG, "│   │   ├── ApiService.kt")
        Log.d(TAG, "│   │   └── RetrofitClient.kt")
        Log.d(TAG, "│   ├── model/")
        Log.d(TAG, "│   │   ├── User.kt")
        Log.d(TAG, "│   │   └── Product.kt")
        Log.d(TAG, "│   └── repository/")
        Log.d(TAG, "│       ├── UserRepository.kt")
        Log.d(TAG, "│       └── ProductRepository.kt")
        Log.d(TAG, "├── user/")
        Log.d(TAG, "│   ├── UserContract.kt")
        Log.d(TAG, "│   ├── UserPresenter.kt")
        Log.d(TAG, "│   ├── UserModel.kt")
        Log.d(TAG, "│   ├── UserListActivity.kt")
        Log.d(TAG, "│   └── UserDetailActivity.kt")
        Log.d(TAG, "├── product/")
        Log.d(TAG, "│   ├── ProductContract.kt")
        Log.d(TAG, "│   ├── ProductPresenter.kt")
        Log.d(TAG, "│   ├── ProductModel.kt")
        Log.d(TAG, "│   ├── ProductListActivity.kt")
        Log.d(TAG, "│   └── ProductDetailActivity.kt")
        Log.d(TAG, "└── di/")
        Log.d(TAG, "    ├── AppComponent.kt")
        Log.d(TAG, "    └── PresenterModule.kt")
        Log.d(TAG, "")
        Log.d(TAG, "模块划分原则：")
        Log.d(TAG, "  1. 每个功能模块有独立的 Contract、Presenter、Model")
        Log.d(TAG, "  2. 共享代码放在 base 或 data 包中")
        Log.d(TAG, "  3. 清晰的包名便于代码导航")
        Log.d(TAG, "  4. 每个模块可以独立编译和测试")
        Log.d(TAG, "")
        Log.d(TAG, "=================================")
    }
    
    /**
     * 演示基类设计
     * 设计原因：说明如何使用基类减少重复代码
     * 技术目的：提供可复用的 MVP 基类实现
     */
    private fun demonstrateBaseClassDesign() {
        Log.d(TAG, "")
        Log.d(TAG, "========== 基类设计 ==========")
        Log.d(TAG, "")
        Log.d(TAG, "// 1. BaseView 接口")
        Log.d(TAG, "interface BaseView {")
        Log.d(TAG, "    fun showLoading()")
        Log.d(TAG, "    fun hideLoading()")
        Log.d(TAG, "    fun showError(message: String)")
        Log.d(TAG, "    fun showMessage(message: String)")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 2. BasePresenter 类")
        Log.d(TAG, "abstract class BasePresenter<V : BaseView> {")
        Log.d(TAG, "    protected var view: V? = null")
        Log.d(TAG, "        private set")
        Log.d(TAG, "")
        Log.d(TAG, "    val isViewAttached: Boolean")
        Log.d(TAG, "        get() = view != null")
        Log.d(TAG, "")
        Log.d(TAG, "    fun attachView(view: V) {")
        Log.d(TAG, "        this.view = view")
        Log.d(TAG, "        onViewAttached()")
        Log.d(TAG, "    }")
        Log.d(TAG, "")
        Log.d(TAG, "    fun detachView() {")
        Log.d(TAG, "        onViewDetached()")
        Log.d(TAG, "        this.view = null")
        Log.d(TAG, "    }")
        Log.d(TAG, "")
        Log.d(TAG, "    protected open fun onViewAttached() {}")
        Log.d(TAG, "    protected open fun onViewDetached() {}")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 3. BasePresenterImpl 实现")
        Log.d(TAG, "abstract class BasePresenterImpl<V : BaseView> : BasePresenter<V>() {")
        Log.d(TAG, "    protected val disposables = CompositeDisposable()")
        Log.d(TAG, "")
        Log.d(TAG, "    override fun detachView() {")
        Log.d(TAG, "        disposables.clear()")
        Log.d(TAG, "        super.detachView()")
        Log.d(TAG, "    }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 4. BaseActivity 类")
        Log.d(TAG, "abstract class BaseActivity<V : BaseView, P : BasePresenter<V>> : AppCompatActivity(), BaseView {")
        Log.d(TAG, "    protected lateinit var presenter: P")
        Log.d(TAG, "")
        Log.d(TAG, "    abstract fun createPresenter(): P")
        Log.d(TAG, "")
        Log.d(TAG, "    override fun onCreate(savedInstanceState: Bundle?) {")
        Log.d(TAG, "        super.onCreate(savedInstanceState)")
        Log.d(TAG, "        presenter = createPresenter()")
        Log.d(TAG, "        presenter.attachView(this as V)")
        Log.d(TAG, "    }")
        Log.d(TAG, "")
        Log.d(TAG, "    override fun onDestroy() {")
        Log.d(TAG, "        presenter.detachView()")
        Log.d(TAG, "        super.onDestroy()")
        Log.d(TAG, "    }")
        Log.d(TAG, "")
        Log.d(TAG, "    override fun showLoading() { progressBar.visibility = View.VISIBLE }")
        Log.d(TAG, "    override fun hideLoading() { progressBar.visibility = View.GONE }")
        Log.d(TAG, "    override fun showError(message: String) {")
        Log.d(TAG, "        Snackbar.make(rootView, message, Snackbar.LENGTH_LONG).show()")
        Log.d(TAG, "    }")
        Log.d(TAG, "    override fun showMessage(message: String) {")
        Log.d(TAG, "        Toast.makeText(this, message, Toast.LENGTH_SHORT).show()")
        Log.d(TAG, "    }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 5. 使用示例")
        Log.d(TAG, "class UserListActivity : BaseActivity<UserListContract.View, UserListContract.Presenter>(),")
        Log.d(TAG, "    UserListContract.View {")
        Log.d(TAG, "")
        Log.d(TAG, "    override fun createPresenter() = UserListPresenter(userRepository)")
        Log.d(TAG, "")
        Log.d(TAG, "    override fun onCreate(savedInstanceState: Bundle?) {")
        Log.d(TAG, "        super.onCreate(savedInstanceState)")
        Log.d(TAG, "        // 直接使用 presenter，不需要手动 attach/detach")
        Log.d(TAG, "        presenter.loadUsers()")
        Log.d(TAG, "    }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "=================================")
    }
    
    /**
     * 演示依赖注入
     * 设计原因：说明如何在 MVP 中使用依赖注入
     * 技术目的：提供解耦的 MVP 实现方式
     */
    private fun demonstrateDependencyInjection() {
        Log.d(TAG, "")
        Log.d(TAG, "========== 依赖注入 ==========")
        Log.d(TAG, "")
        Log.d(TAG, "// 1. 使用 Dagger2 进行依赖注入")
        Log.d(TAG, "")
        Log.d(TAG, "// 定义 App Component")
        Log.d(TAG, "@Singleton")
        Log.d(TAG, "@Component(modules = [AppModule::class, NetworkModule::class])")
        Log.d(TAG, "interface AppComponent {")
        Log.d(TAG, "    fun inject(activity: UserListActivity)")
        Log.d(TAG, "    fun inject(activity: ProductListActivity)")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 定义 Presenter Module")
        Log.d(TAG, "@Module")
        Log.d(TAG, "class PresenterModule {")
        Log.d(TAG, "    @Provides")
        Log.d(TAG, "    @Singleton")
        Log.d(TAG, "    fun provideUserPresenter(")
        Log.d(TAG, "        userRepository: UserRepository")
        Log.d(TAG, "    ): UserContract.Presenter {")
        Log.d(TAG, "        return UserPresenter(userRepository)")
        Log.d(TAG, "    }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 2. 在 Activity 中使用注入")
        Log.d(TAG, "class UserListActivity : BaseActivity<UserListContract.View, UserListContract.Presenter>(),")
        Log.d(TAG, "    UserListContract.View {")
        Log.d(TAG, "    ")
        Log.d(TAG, "    @Inject")
        Log.d(TAG, "    lateinit var presenter: UserContract.Presenter")
        Log.d(TAG, "    ")
        Log.d(TAG, "    override fun onCreate(savedInstanceState: Bundle?) {")
        Log.d(TAG, "        AndroidInjection.inject(this)")
        Log.d(TAG, "        super.onCreate(savedInstanceState)")
        Log.d(TAG, "    }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 3. 使用 Kotlin 委托进行依赖注入")
        Log.d(TAG, "class UserListActivity : BaseActivity<UserListContract.View, UserListContract.Presenter>(),")
        Log.d(TAG, "    UserListContract.View,")
        Log.d(TAG, "    by dagger2Inject() { // 自定义委托")
        Log.d(TAG, "    ")
        Log.d(TAG, "    override val presenter: UserContract.Presenter by inject()")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 4. Koin - 轻量级依赖注入")
        Log.d(TAG, "val presenterModule = module {")
        Log.d(TAG, "    single { UserRepository(api) }")
        Log.d(TAG, "    single { UserPresenter(get()) }")
        Log.d(TAG, "    viewModel { UserListViewModel(get()) }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "class UserListActivity : BaseActivity(), UserContract.View {")
        Log.d(TAG, "    private val presenter: UserContract.Presenter by inject()")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "=================================")
    }
    
    /**
     * 演示单元测试
     * 设计原因：说明如何对 MVP 进行单元测试
     * 技术目的：提供可测试的 MVP 实现方式
     */
    private fun demonstrateUnitTesting() {
        Log.d(TAG, "")
        Log.d(TAG, "========== 单元测试 ==========")
        Log.d(TAG, "")
        Log.d(TAG, "// 1. 创建 Mock View")
        Log.d(TAG, "class MockUserListView : UserContract.View {")
        Log.d(TAG, "    var loadingShown = false")
        Log.d(TAG, "    var loadingHidden = false")
        Log.d(TAG, "    var users: List<User>? = null")
        Log.d(TAG, "    var error: String? = null")
        Log.d(TAG, "")
        Log.d(TAG, "    override fun showLoading() { loadingShown = true }")
        Log.d(TAG, "    override fun hideLoading() { loadingHidden = true }")
        Log.d(TAG, "    override fun showUsers(users: List<User>) { this.users = users }")
        Log.d(TAG, "    override fun showError(message: String) { this.error = message }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 2. 创建 Mock Model")
        Log.d(TAG, "class MockUserRepository : UserRepository {")
        Log.d(TAG, "    var usersToReturn = listOf<User>()")
        Log.d(TAG, "    var errorToThrow: Exception? = null")
        Log.d(TAG, "    ")
        Log.d(TAG, "    override suspend fun getUsers(): Result<List<User>> {")
        Log.d(TAG, "        return if (errorToThrow != null) {")
        Log.d(TAG, "            Result.failure(errorToThrow!!)")
        Log.d(TAG, "        } else {")
        Log.d(TAG, "            Result.success(usersToReturn)")
        Log.d(TAG, "        }")
        Log.d(TAG, "    }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 3. 测试 Presenter")
        Log.d(TAG, "@RunWith(MockitoJUnitRunner::class)")
        Log.d(TAG, "class UserListPresenterTest {")
        Log.d(TAG, "    ")
        Log.d(TAG, "    @Mock")
        Log.d(TAG, "    lateinit var mockView: MockUserListView")
        Log.d(TAG, "    ")
        Log.d(TAG, "    @InjectMockSpy")
        Log.d(TAG, "    lateinit var mockRepository: MockUserRepository")
        Log.d(TAG, "    ")
        Log.d(TAG, "    lateinit var presenter: UserListPresenter")
        Log.d(TAG, "    ")
        Log.d(TAG, "    @Before")
        Log.d(TAG, "    fun setup() {")
        Log.d(TAG, "        presenter = UserListPresenter(mockRepository)")
        Log.d(TAG, "        presenter.attachView(mockView)")
        Log.d(TAG, "    }")
        Log.d(TAG, "    ")
        Log.d(TAG, "    @Test")
        Log.d(TAG, "    fun `loadUsers success`() {")
        Log.d(TAG, "        // Given")
        Log.d(TAG, "        val users = listOf(User(\"1\", \"John\"), User(\"2\", \"Jane\"))")
        Log.d(TAG, "        mockRepository.usersToReturn = users")
        Log.d(TAG, "        ")
        Log.d(TAG, "        // When")
        Log.d(TAG, "        presenter.loadUsers()")
        Log.d(TAG, "        ")
        Log.d(TAG, "        // Then")
        Log.d(TAG, "        assertTrue(mockView.loadingShown)")
        Log.d(TAG, "        assertTrue(mockView.loadingHidden)")
        Log.d(TAG, "        assertEquals(users, mockView.users)")
        Log.d(TAG, "    }")
        Log.d(TAG, "    ")
        Log.d(TAG, "    @Test")
        Log.d(TAG, "    fun `loadUsers error`() {")
        Log.d(TAG, "        // Given")
        Log.d(TAG, "        mockRepository.errorToThrow = Exception(\"Network error\")")
        Log.d(TAG, "        ")
        Log.d(TAG, "        // When")
        Log.d(TAG, "        presenter.loadUsers()")
        Log.d(TAG, "        ")
        Log.d(TAG, "        // Then")
        Log.d(TAG, "        assertTrue(mockView.loadingShown)")
        Log.d(TAG, "        assertTrue(mockView.loadingHidden)")
        Log.d(TAG, "        assertEquals(\"Network error\", mockView.error)")
        Log.d(TAG, "    }")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "// 4. 使用 Kotlin Coroutines 测试")
        Log.d(TAG, "@Test")
        Log.d(TAG, "fun `loadUsers with coroutines`() = runBlocking {")
        Log.d(TAG, "    // Given")
        Log.d(TAG, "    val users = listOf(User(\"1\", \"John\"))")
        Log.d(TAG, "    `when`(repository.getUsers()).thenReturn(Result.success(users))")
        Log.d(TAG, "    ")
        Log.d(TAG, "    // When")
        Log.d(TAG, "    presenter.loadUsers()")
        Log.d(TAG, "    ")
        Log.d(TAG, "    // Then")
        Log.d(TAG, "    verify(view).showLoading()")
        Log.d(TAG, "    verify(view).hideLoading()")
        Log.d(TAG, "    verify(view).showUsers(users)")
        Log.d(TAG, "}")
        Log.d(TAG, "")
        Log.d(TAG, "=================================")
    }
    
    /**
     * 演示最佳实践
     * 设计原因：总结 MVP 的最佳实践
     * 技术目的：帮助写出高质量的 MVP 代码
     */
    private fun demonstrateBestPractices() {
        Log.d(TAG, "")
        Log.d(TAG, "========== 最佳实践 ==========")
        Log.d(TAG, "")
        Log.d(TAG, "1. 契约类设计")
        Log.d(TAG, "   - 每个模块使用独立的 Contract 接口")
        Log.d(TAG, "   - View 只包含 UI 相关方法")
        Log.d(TAG, "   - Presenter 只包含业务逻辑方法")
        Log.d(TAG, "   - 使用泛型提高代码复用")
        Log.d(TAG, "")
        Log.d(TAG, "2. 生命周期管理")
        Log.d(TAG, "   - 在 onCreate 中 attachView")
        Log.d(TAG, "   - 在 onDestroy 中 detachView")
        Log.d(TAG, "   - 使用 try-finally 确保资源释放")
        Log.d(TAG, "   - 处理好配置变更（如屏幕旋转）")
        Log.d(TAG, "")
        Log.d(TAG, "3. 错误处理")
        Log.d(TAG, "   - Presenter 处理所有业务逻辑错误")
        Log.d(TAG, "   - View 只负责显示错误信息")
        Log.d(TAG, "   - 使用 Result 类型封装成功/失败")
        Log.d(TAG, "   - 提供友好的错误提示")
        Log.d(TAG, "")
        Log.d(TAG, "4. 线程管理")
        Log.d(TAG, "   - Model 在后台线程执行")
        Log.d(TAG, "   - Presenter 在主线程更新 View")
        Log.d(TAG, "   - 使用 Coroutines 或 RxJava 管理线程")
        Log.d(TAG, "   - 处理好请求取消")
        Log.d(TAG, "")
        Log.d(TAG, "5. 代码组织")
        Log.d(TAG, "   - 清晰的包结构")
        Log.d(TAG, "   - 遵循单一职责原则")
        Log.d(TAG, "   - 使用有意义的方法名")
        Log.d(TAG, "   - 添加必要的注释")
        Log.d(TAG, "")
        Log.d(TAG, "6. 性能优化")
        Log.d(TAG, "   - 避免在 Presenter 中存储大型对象")
        Log.d(TAG, "   - 及时取消不需要的网络请求")
        Log.d(TAG, "   - 使用内存缓存减少重复请求")
        Log.d(TAG, "   - 懒加载非关键数据")
        Log.d(TAG, "")
        Log.d(TAG, "7. 测试性")
        Log.d(TAG, "   - Presenter 不依赖 Android SDK")
        Log.d(TAG, "   - 使用接口解耦依赖")
        Log.d(TAG, "   - 编写单元测试覆盖核心逻辑")
        Log.d(TAG, "   - 使用 Mock 对象进行隔离测试")
        Log.d(TAG, "")
        Log.d(TAG, "=================================")
    }
}
